name: Professional CI Pipeline for Spring Boot with Maven  
  
on:  
  push:  
    branches:  
      - main  
  pull_request:  
    branches:  
      - main  
  
jobs:  
  build:  
    name: CI for Spring Boot (Maven)  
    runs-on: ubuntu-latest  
  
    steps:  
      - name: Checkout source code  
        uses: actions/checkout@v4  
  
      - name: Set up Temurin JDK 17  
        uses: actions/setup-java@v4  
        with:  
          distribution: 'temurin'  
          java-version: 17  
  
      - name: Cache Maven dependencies  
        uses: actions/cache@v4  
        with:  
          path: ~/.m2  
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}  
          restore-keys: |  
            ${{ runner.os }}-maven  
  
      - name: Run tests with coverage  
        run: mvn clean verify jacoco:report -B  
  
      - name: Build the Application  
        run: mvn package -B -DskipTests  
  
      - name: Upload JAR artifacts  
        uses: actions/upload-artifact@v4  
        with:  
          name: spring-boot-jar  
          path: target/*.jar  
          retention-days: 30  
  
      - name: Upload coverage reports  
        uses: actions/upload-artifact@v4  
        if: always()  
        with:  
          name: coverage-report  
          path: target/site/jacoco/  
          retention-days: 30